### ISSUE TITLE
Make QBO logs dir configurable

### ISSUE THREAD

**Issue by ananelson** [agileware/au.com.agileware.civiquickbooks#11]
When I attempt to authorize, I get this error message:

```
DirectoryIterator::__construct(/tmp): failed to open dir: Permission denied
```

This is due to the QBO PHP API attempting to write logs to `/tmp/IdsLogs`, which is not writable for my installation. It would be great if this log location could be specified in settings.

https://github.com/agileware/au.com.agileware.civiquickbooks/blob/bfcf7e5b56d661c9dcca93167241d1970f20be57/vendor/quickbooks/v3-php-sdk/src/sdk.config#L27

**Comment by ananelson** [comment]
(I've worked around this for now by hard-coding a log location.)

**Comment by ananelson** [comment]
I've resolved this in my branch, will submit a PR soon.

**Comment by agileware-fj** [comment]
Thanks for the report, @ananelson .

As you've quoted a source location inside a bundled vendor package, fixing it in this location has integration implications for future upgrades of the SDK – can you advise if your resolution is modifying this file, or managed to work around it?

**Comment by ananelson** [comment]
My fix does not involve changing the vendor's code! :) 

They provide setLogLocation and disableLog functions.

```
+    $dataService->setLogLocation($logLocation);
+    if (!$logActivated) {
+        $dataService->disableLog();
+    }
```

**Comment by agileware-fj** [comment]
Merged referencing PR.
