### ISSUE TITLE
Trouble authorizing

### ISSUE THREAD

**Issue by JoeMurray** [agileware/au.com.agileware.civiquickbooks#16]
1. In Installation instructions step 1 (https://github.com/agileware/au.com.agileware.civiquickbooks/tree/2.6), one finds:

> You will need an Intuit Developer Account, sign up at (https://developer.intuit.com/). This
> account must be linked to the QuickBooks Online company you wish to integrate with.

It is not clear what it means to "link" an account between Intuit Developer and QuickBooks Online, and how I can check if accounts created in both places with same email are linked.

2. If the above is not the issue, then I am having separate issue when trying to authorize. 

I have configured the callback as follows:
![2020-08-18_12-33-03](https://user-images.githubusercontent.com/300943/90541242-4fc27a00-e150-11ea-8623-5be0cd8cfc42.png)

For reference, here is the value in the Settings page:
![2020-08-18_12-43-46](https://user-images.githubusercontent.com/300943/90541371-826c7280-e150-11ea-8dc9-79ae13fdbdc4.png)

When I click on the Authorize link above I get the following error:
![2020-08-18_12-33-28](https://user-images.githubusercontent.com/300943/90541482-b5af0180-e150-11ea-92a3-9f3e10da1948.png)

The browser url, in case this is useful, is https://appcenter.intuit.com/app/connect/oauth2/error?client_id=ABdwI5q6AegPEt9nuJbzGrE1STTTMCL9oEodqdZKQ0cXJBvk5n&scope=com.intuit.quickbooks.accounting&redirect_uri=https%3A%2F%2Fquickbooks.jmaconsulting.biz%2Fcivicrm%2Fquickbooks%2FOAuth&response_type=code&state=%7B%22state_token%22%3A%22LmQNIuFeNJYjLMWpkDngHfws9cQG7GLCe7X1kYyf%22%7D

There are no errors in the Apache log.

**Comment by agileware-justin** [comment]
> It is not clear what it means to "link" an account between Intuit Developer and QuickBooks Online, and how I can check if accounts created in both places with same email are linked.

I have updated the README to clarify: This account must be added as a user of "Admin" user type to the QuickBooks Online company being integrated.

You can check that access has been granted by:

1. Login to https://developer.intuit.com/
2. Go to the section, Production, Keys & OAuth
3. Below the Production Companies sub-heading, there is a link, View Production companies
4. Click View Production companies
5. Your QuickBooks Online company should load or be available for selection if linked to more than one.

**Comment by agileware-justin** [comment]
When I go to https://quickbooks.jmaconsulting.biz/civicrm/quickbooks/OAuth it returns "access denied"

The Redirect URI looks fine to me.

**Comment by agileware-justin** [comment]
The Redirect URI looks fine to me.

**Comment by JoeMurray** [comment]
Thanks, @agileware-justin . When I click on View Production Companies, I end up in the QBO account.

My email is the User ID for the Intuit account for Developer and the Production Company. I changed the Drupal user name from admin to the email. I believe that was the only change I made, and now I get the following error when I try to Authorize from the Settings page:

![2020-08-18_18-24-18](https://user-images.githubusercontent.com/300943/90571581-10ac1d00-e180-11ea-8103-6ff9f178a336.png)

I've rechecked and the redirect_uri is still the same as shown above.

**Comment by agileware-justin** [comment]
So just to confirm, in the Quickbooks Developer account these are all set?

- Keys, Client ID
- Keys, Client Secret
- Redirect URI

Because I am looking at our Quickbooks Developer account. And that's what we have set up.

Maybe it's a configuration issue on the CiviCRM side of the conversation. But I don't know what that would be, since there's nothing to edit there at all.

**Comment by agileware-justin** [comment]
@JoeMurray yep, that would do it! Happy to help, have a great weekend mate.
