### ISSUE TITLE
Overwrites other extension menu items

### ISSUE THREAD

**Issue by mattwire** [agileware/au.com.agileware.civiquickbooks#17]
If you install another extension that adds a menu-item to the Administer menu and then install this one it will get overwritten (depending on the load order of the hooks which is normally deterministic per-site but not guaranteed).

In this case, install civirules and quickbooks and the civirules menu entry disappears.

This can be fixed by switching to more current menu hook code per examples:
1. https://lab.civicrm.org/extensions/dataprocessor/-/blob/master/dataprocessor.php#L285
2. https://lab.civicrm.org/extensions/stripe/-/blob/master/stripe.php#L215

**Comment by agileware-justin** [comment]
Thanks @mattwire have bugged it, Agileware Ref: CIVIQBO-80

**Comment by agileware-justin** [comment]
Fixed by https://github.com/agileware/au.com.agileware.civiquickbooks/pull/18
