### ISSUE TITLE
QBO logs dir must end with /

### ISSUE THREAD

**Issue by ananelson** [agileware/au.com.agileware.civiquickbooks#19]
I'll try to work on this... if QBO logging is enabled with a custom path (#11 #15), then the custom path must end in a / otherwise weirdness happens. Probably easiest to just add a trailing "/" to the value if not provided.

**Comment by agileware-justin** [comment]
Just marking this old issue as closed, since we're not planning on working on this one (and doesn't seem anyone is either).
