### ISSUE TITLE
catching generic Exception object can lead to inaccurate errors

### ISSUE THREAD

**Issue by ananelson** [agileware/au.com.agileware.civiquickbooks#21]
I will probably do a patch for this soon.

Don't do:
```
 } catch (Exception $e) {
// assume specific type of exception was caught
```

Instead do:
```
 } catch (SpecificException $e) {
// assume specific type of exception was caught
```

If need to catch generic exception also that can happen in 2nd catch.

**Comment by agileware-justin** [comment]
Just marking this old issue as closed, since we're not planning on working on this one (and doesn't seem anyone is either).
