### ISSUE TITLE
Trouble authorizing

### ISSUE THREAD

**Issue by stevemacguy** [agileware/au.com.agileware.civiquickbooks#3]
I have been trying to connect CiviCRM and QuickBooks Online using this extension. I have followed the instructions (I think) but can't get past the authorization. I entered the production keys on the settings page, but when I click AUTHORIZE, I get the error message (from QuickBooks) "We're sorry! We're experiencing some problems. Please try again later."

Any idea what I might be doing wrong? There isn't something I am missing about a redirect URI, is there? Thank you!

**Comment by jusfreeman** [comment]
@stevemacguy have you tried contacting QuickBooks support about this issue? Sounds like it's account related.

**Comment by stevemacguy** [comment]
Thank you. I'll give it a shot.

Are there examples of this extension working in the United States?

**Comment by jusfreeman** [comment]
> Are there examples of this extension working in the United States?

@stevemacguy we're based on Australia and so have tested this using Australian QBO users - it works fine.. This extension uses the QBO API to connect to the QBO services, I'm not aware of any specific reason as to why it "would not work in the US" - it should work.

If you need assistance from someone more in your timezone and part of the world, I can recommend @JoeMurray from http://jmaconsulting.biz/

**Comment by joseltorres** [comment]
I am having this same issue, have anyone ever figured this out? 
I am in the US

**Comment by stevemacguy** [comment]
I haven't.

**Comment by JoeMurray** [comment]
We're going to try working on this later this month. @monishdeb

**Comment by jusfreeman** [comment]
QuickBooks Online changed to using the OAuth 2.0 protocol, so all new connected apps must use this protocol for authentication. CiviQuickBooks version 2 implements the OAuth 2.0, so make sure you are using the 2.0 tag, https://github.com/agileware/au.com.agileware.civiquickbooks/tree/2.0

If this is still failing then please post your steps and screenshots to help with any investigation.

**Comment by stevemacguy** [comment]
I got the authorization to work (but have no gone further than that). I noticed that this time the setup page gave me a redirect URL to use in the QBs app. I do not believe that was there before (see my first comment). I'll let you know how the rest of the integration goes.

**Comment by jusfreeman** [comment]
@stevemacguy your experience is in-line with my previous comment. QBO changed how apps are connected.

**Comment by lyonsdigital** [comment]
Looking for any updates on this topic. I've managed to verify our site with Intuit, but I can't move past that step. When I try connecting from the sandbox, I get a message that the connection failed. What am I missing (beside more documentation)?

**Comment by stevemacguy** [comment]
You are using the development (and not the production) keys from Intuit?

**Comment by lyonsdigital** [comment]
Yes, If there's a separate set of keys for production, I haven't even seen them yet in this process.

**Comment by stevemacguy** [comment]
You are choosing launch under the app in QuickBooks? That didn't work for me, either. But I don't know if it even matters. I experimented for a few days with the whole thing and eventually gave up. I wish there was a way to confirm the connection without having to be positive that all the setting are exactly right. 

At this point I've decided to just classify transactions in bulk from the payment processor, so I have likely moved beyond trying to get this to work anyway.

**Comment by lyonsdigital** [comment]
That's a disappointment.

**Comment by jusfreeman** [comment]
@lyonsdigital can you provide a screenshot of where in the authorisation process you are stuck?

**Comment by lyonsdigital** [comment]
I have verified the redirect and I want to sync the chart of accounts but I'm getting a message that the server can't be found. In this image,  you can see the chart of accounts for the sandbox and the Civi config screen. Do you need an image of the specific error?

![quickbooks_screens](https://user-images.githubusercontent.com/3308002/58336842-86f19080-7e12-11e9-9193-cdc8676390ef.png)

**Comment by jusfreeman** [comment]
@lyonsdigital thanks mate

Are you able to copy an excerpt of the error from the civicrm.log file? Screenshot of the error and the page where you receive it also useful.

If you have time, try doing a screen recording of the authorisation process and post it here, this tool is useful https://www.hyfy.io/

**Comment by lyonsdigital** [comment]
Here's the error that I'm getting when I try to connect from the sandbox. All I'm doing is selecting my app and clicking on launch. I feel as if I've missed a step.

![Screen Shot 2019-05-24 at 4 01 13 PM](https://user-images.githubusercontent.com/3308002/58353789-65f26500-7e3d-11e9-8b93-1f763a75eb6f.png)

**Comment by jusfreeman** [comment]
@lyonsdigital I can see that https://fppta.org is a WordPress website, that's OK as we have verified QBO CiviCRM on WordPress.

Is there anything at all that may be interfering with the OAuth 2.0 communication process between Intuit and your CiviCRM site? WordFence? CloudFlare? Firewall?

Because on that last screen, it should only take a few seconds to establish the authentication between Intuit and your CiviCRM site.

Check your web access logs to verify that you can see Intuit requests to your CiviCRM site - there should be requests from Intuit. You may see a HTTP 500 as a response to the request, if so then there may be more information in the web server error log file.

Again, check the CiviCRM log file (ConfigandLogs) and provide an excerpt of the error messages (if any).

**Comment by lyonsdigital** [comment]
We are about to observe the Memorial Day holiday in the US, and I'm shutting down. I appreciate you taking your morning to look at this. I will report back when I get back on Tuesday (I believe your Wednesday). Thank you so much.

**Comment by jusfreeman** [comment]
@lyonsdigital assuming that everything is OK now since there's not been anymore reports of issues. So I'll close this request.
