### ISSUE TITLE
Set up complexities resulting from changes with the QB developer account

### ISSUE THREAD

**Issue by Upperholme** [agileware/au.com.agileware.civiquickbooks#39]
I'm just trying to get this extension configured on a new site. Getting production keys for the app via the QB developer account is now a relatively complex process it seems, requiring that I answer a lot of questions about "my" app. Hoping that I've answered the questions correctly I'm currently presumably awaiting some sort of review and hopefully at some unspecified point in the future (I see no indication as to whether it will take minutes or months for them to complete their review) then I will be given access to the production credentials.

Of course I may have answered some of the questions wrongly - I'm using educated guesswork here - in which case they may choose to refuse my app, which would be a good deal of time wasted.

It looks like their entire developer account set-up is geared to the needs of larger scale app developers who want to produce an app that can then be marketed through some sort of add-on marketplace. If I learn more I'll attempt to make some notes that might inform an update to the readme.

**Comment by Upperholme** [comment]
So in the ned it didn't take too long to get a result - maybe an hour, perhaps even less (i went and did something else). And I got a result. I'll endeavour to make a few notes and consider a PR for the Readme to help others.

**Comment by agileware-fj** [comment]
@Upperholme did you get anywhere with this? We would be very happy to receive a PR on the documentation.
