### ISSUE TITLE
TLS 1.2 error on authorizing 

### ISSUE THREAD

**Issue by netzih** [agileware/au.com.agileware.civiquickbooks#4]
Getting error Error. 
Checking TLS 1.2 version failed. Please make sure your PHP cURL supports TSL 1.2.
My PHP version supports TLS V1.2

CiviCRM version 5.15.0 
extension version 2.0 
PHP version 7.2.19-1+ubuntu18.04.1
PHP_curl 7.2.20
OPENSSL 1.1.1

When testing curl https://tlstest.paypal.com/ It's coming back "PayPal_Connection_OK" So TLS v1.2 is definitely OK.

(Also should probably fix second TLS from TSL in message).

**Comment by jusfreeman** [comment]
> Checking TLS 1.2 version failed. Please make sure your PHP cURL supports TSL 1.2.

This error is being generated by the official QuickBooks PHP SDK. And it's also where the typo is "TSL" vs "TLS".

See https://github.com/agileware/au.com.agileware.civiquickbooks/blob/master/vendor/quickbooks/v3-php-sdk/src/Core/HttpClients/CurlHttpClient.php#L150

I've submitted a PR to fix the typo, see https://github.com/intuit/QuickBooks-V3-PHP-SDK/pull/238

In terms of what exactly is causing that error, sorry I don't know it is likely either:
1. A problem specific to your environment, OR
2. A bug in the QuickBooks PHP SDK

As we've not seen any other problems like this with the QuickBooks PHP SDK, I am inclined to suspect it is an environment issue.

Agileware Ref: CIVIQBO-47

**Comment by netzih** [comment]
Any way around it to be able to use the extension?

**Comment by jusfreeman** [comment]
@netzih do you have an SSL certificate installed on the website where the QBO extension is installed?

**Comment by netzih** [comment]
> @netzih do you have an SSL certificate installed on the website where the QBO extension is installed?

I believe I do . 
I'm using let's encrypt ssl.

**Comment by jusfreeman** [comment]
@netzih so just to summarise, the QuickBooks PHP SDK is returning a TLS 1.2 version check failure, when it tries to confirm that TLS 1.2 or higher is available on your website SSL connection.

My suggestion would be to execute curl on the same server to connect to the website URL and check the TLS status.

**Comment by netzih** [comment]
What website url would I attempt to connect to? When I tried connecting to PayPal it came back with success.

**Comment by jusfreeman** [comment]
@netzih the TLS 1.2 verification check is being performed on the website where CiviCRM is installed, so that's where you need to verify. Not PayPal.

**Comment by netzih** [comment]
Pretty sure it is.
How can I check?

**Comment by netzih** [comment]
Just checked.
Definitely has tls1.2 on the server.

**Comment by jusfreeman** [comment]
@netzih how about this suggestion, add code to print out the value of $tlsVersion on this line and paste the results here. See https://github.com/agileware/au.com.agileware.civiquickbooks/blob/master/vendor/quickbooks/v3-php-sdk/src/Core/HttpClients/CurlHttpClient.php#L148

**Comment by netzih** [comment]
> @netzih how about this suggestion, add code to print out the value of $tlsVersion on this line and paste the results here. See https://github.com/agileware/au.com.agileware.civiquickbooks/blob/master/vendor/quickbooks/v3-php-sdk/src/Core/HttpClients/CurlHttpClient.php#L148

Had it added but it's not giving me the info still just says "Error. Checking TLS 1.2 version failed. Please make sure your PHP cURL supports TSL 1.2"

**Comment by netzih** [comment]
Fixed the issue by changing the CurlHttpClient.php to https://github.com/intuit/QuickBooks-V3-PHP-SDK/pull/209/commits/9d42136d0fc45864ecd8a3e22ad607e483ef04f1

Should consider updating the file here as well

**Comment by jusfreeman** [comment]
Good find @netzih well done 👍

**Comment by netzih** [comment]
> Good find @netzih well done

Thanx @jusfreeman created a pr to commit. Hope it can help others.

**Comment by jusfreeman** [comment]
I can see that the PR has been merged, https://github.com/intuit/QuickBooks-V3-PHP-SDK/pull/209

So the solution would be to update the bundled library to QBO 5.0.5 which includes this plus other fixes.

**Comment by netzih** [comment]
Yes. I only updated those 3 lines though. And it worked.
