### ISSUE TITLE
Can't find Redirect URI

### ISSUE THREAD

**Issue by Upperholme** [agileware/au.com.agileware.civiquickbooks#40]
In the Readme for this extension, under the Configuration subheading, it says "copy the Redirect URI that is present...". I'm following the instructions closely, but can see no Redirect URI. clearly I can't go further without this, as the Quickbooks developer site needs this before it will begin to operate. 

Maybe I'm missing something obvious? The Readme sort of implies that having entered my client key and secret into the Quickbooks Online Settings form on my site, and hit the Submit button, I will in some way be presented with the Redirect URI, but clearly that's not happening.

Howe do I go about finding this URI?

**Comment by Upperholme** [comment]
Looking through old closed issues I see that https://github.com/agileware/au.com.agileware.civiquickbooks/issues/16 includes a screenshot that shows that when the settings page is submitted with keys entered it is supposed to disoplay the Redirect URI in a yellow box. This isn't happening in my case. No idea why not. It would be super helpful to include a screenshot like this in the Readme so that people new to the extension could understand what to expect.

So maybe this issue should be more about why this yeallow box with the Redirect URI isn't being displayed. For info I'm running with Civi 5.57 now (was 5.53 when I first tried to get this extension set up), and the host CMS is Wordpress. PHP is 7.4.x

**Comment by agileware-fj** [comment]
Can't reproduce this issue on CiviCRM 5.72.1

Assuming this is no longer a problem, let us know if not.
