### ISSUE TITLE
We are see an issue with civi HTML checkbox preventing the QB ext settings from loading...

### ISSUE THREAD

**Issue by mferraznw** [agileware/au.com.agileware.civiquickbooks#42]
TypeError: strlen(): Argument #1 ($str) must be of type string, array given in HTML_QuickForm_checkbox->toHtml() (line 138 of /home/astronomyhouston/www/drupal9/vendor/civicrm/civicrm-packages/HTML/QuickForm/checkbox.php)#0 /home/astronomyhouston/www/drupal9/vendor/civicrm/civicrm-packages/HTML/QuickForm/Renderer/Array.php(307): HTML_QuickForm_checkbox->toHtml() #1 /home/astronomyhouston/www/drupal9/vendor/civicrm/civicrm-packages/HTML/QuickForm/Renderer/ArraySmarty.php(189): HTML_QuickForm_Renderer_Array->_elementToArray(Object(HTML_QuickForm_checkbox), false, NULL) #2 /home/astronomyhouston/www/drupal9/vendor/civicrm/civicrm-core/CRM/Core/Form/Renderer.php(87): HTML_QuickForm_Renderer_ArraySmarty->_elementToArray(Object(HTML_QuickForm_checkbox), false, NULL) #3 /home/astronomyhouston/www/drupal9/vendor/civicrm/civicrm-packages/HTML/QuickForm/Renderer/Array.php(221): CRM_Core_Form_Renderer->_elementToArray(Object(HTML_QuickForm_checkbox), false, NULL) #4 /home/astronomyhouston/www/drupal9/vendor/civicrm/civicrm-packages/HTML/QuickForm/element.php(415): HTML_QuickForm_Renderer_Array->renderElement(Object(HTML_QuickForm_checkbox), false, NULL) #5 /home/astronomyhouston/www/drupal9/vendor/civicrm/civicrm-packages/HTML/QuickForm.php(1705): HTML_QuickForm_element->accept(Object(CRM_Core_Form_Renderer), false, NULL) #6 /home/astronomyhouston/www/drupal9/vendor/civicrm/civicrm-core/CRM/Core/Form.php(1136): HTML_QuickForm->accept(Object(CRM_Core_Form_Renderer)) #7 /home/astronomyhouston/www/drupal9/vendor/civicrm/civicrm-core/CRM/Core/QuickForm/Action/Display.php(95): CRM_Core_Form->toSmarty() #8 /home/astronomyhouston/www/drupal9/vendor/civicrm/civicrm-core/CRM/Core/QuickForm/Action/Display.php(83): CRM_Core_QuickForm_Action_Display->renderForm(Object(CRM_Civiquickbooks_Form_Settings)) #9 /home/astronomyhouston/www/drupal9/vendor/civicrm/civicrm-packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Display->perform(Object(CRM_Civiquickbooks_Form_Settings), 'display') #10 /home/astronomyhouston/www/drupal9/vendor/civicrm/civicrm-packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Civiquickbooks_Form_Settings), 'display') #11 /home/astronomyhouston/www/drupal9/vendor/civicrm/civicrm-core/CRM/Core/Controller.php(355): HTML_QuickForm_Page->handle('display') #12 /home/astronomyhouston/www/drupal9/vendor/civicrm/civicrm-core/CRM/Utils/Wrapper.php(98): CRM_Core_Controller->run() #13 /home/astronomyhouston/www/drupal9/vendor/civicrm/civicrm-core/CRM/Core/Invoke.php(292): CRM_Utils_Wrapper->run('CRM_Civiquickbo...', 'QuickBooks Onli...', Array) #14 /home/astronomyhouston/www/drupal9/vendor/civicrm/civicrm-core/CRM/Core/Invoke.php(69): CRM_Core_Invoke::runItem(Array) #15 /home/astronomyhouston/www/drupal9/vendor/civicrm/civicrm-core/CRM/Core/Invoke.php(36): CRM_Core_Invoke::_invoke(Array) #16 /home/astronomyhouston/www/drupal9/web/modules/contrib/civicrm/src/Civicrm.php(88): CRM_Core_Invoke::invoke(Array) #17 /home/astronomyhouston/www/drupal9/web/modules/contrib/civicrm/src/Controller/CivicrmController.php(80): Drupal\civicrm\Civicrm->invoke(Array) #18 [internal function]: Drupal\civicrm\Controller\CivicrmController->main(Array, '') #19 /home/astronomyhouston/www/drupal9/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #20 /home/astronomyhouston/www/drupal9/web/core/lib/Drupal/Core/Render/Renderer.php(580): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #21 /home/astronomyhouston/www/drupal9/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #22 /home/astronomyhouston/www/drupal9/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #23 /home/astronomyhouston/www/drupal9/vendor/symfony/http-kernel/HttpKernel.php(169): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #24 /home/astronomyhouston/www/drupal9/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #25 /home/astronomyhouston/www/drupal9/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #26 /home/astronomyhouston/www/drupal9/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #27 /home/astronomyhouston/www/drupal9/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #28 /home/astronomyhouston/www/drupal9/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #29 /home/astronomyhouston/www/drupal9/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #30 /home/astronomyhouston/www/drupal9/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #31 /home/astronomyhouston/www/drupal9/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #32 /home/astronomyhouston/www/drupal9/web/core/lib/Drupal/Core/DrupalKernel.php(713): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #33 /home/astronomyhouston/www/drupal9/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #34 {main}
--

In order to regain access to settings, I need to update the above mentioned line to:

        if (gettype($this) == "string" && 0 == strlen($this->_text ?? '')) {

**Comment by agileware-justin** [comment]
> the above mentioned line

@mferraznw which line exactly and what file are you referring too here?

**Comment by agileware-fj** [comment]
I cannot reproduce this issue, and the settings page definition doesn't specify any arrays for the text property (label) that would cause this.  Marking closed.
