### ISSUE TITLE
Civiquickbooks Contact Push Job errors

### ISSUE THREAD

**Issue by Upperholme** [agileware/au.com.agileware.civiquickbooks#43]
Still trying to get this extension working smoothly. Looking at the scheduled jobs, I'm seeing an error beingf reported every trme the job runs:

Finished execution of Civiquickbooks Contact Push Job with result: Failure, Error message: Contact Push aborted due to: Not all contacts were saved:

Failed to push Contact: 2310 (AccountsContact: ) with error: 'Fax' is not a valid option for field phone_type_id

The second line was repeated, identifying four other contact IDs.

Wondering whether this might be because the phone type 'Fax' was not too long ago removed from the defaults in CiviCRM, I wen and added it as a phone type, then re-ran the scheduled job. This time I see:

Finished execution of Civiquickbooks Contact Push Job with result: Failure, Error message: Contact Push aborted due to: Not all contacts were saved:

Failed to push Contact: 2313 (AccountsContact: ) with error: 'Pager' is not a valid option for field phone_type_id

This time with maybe 20 records listed.

OK, I might be on to something. So I add 'Pager' as another phone type in Civi, and re-run the job again:

Finished execution of Civiquickbooks Contact Push Job with result: Failure, Error message: Contact Push aborted due to: Not all contacts were saved:

Failed to push Contact: 2313 (AccountsContact: ) with error: 'Voicemail' is not a valid option for field phone_type_id

Again with about 20 records getting listed. Wondering how long this is going to go on for, I add 'Voicemail' as a phone type, and re-run, again:

Finished execution of Civiquickbooks Contact Push Job with result: Failure, Error message: Contact Push aborted due to: Not all contacts were saved:

Failed to push Contact: 2313 (AccountsContact: ) with error: Authentication failure doing QBO contact push, aborting

Huh? How can my authentication be failing. The previous runs of this scheduled job seemed to be successful enough at authenticating. What's changed?

Note that contact ID 2313 in my Civi database is a deleted record (not yet permanently deleted). I deleted contact 2313 and the linked contribution record, and tried again. A new record ID was presented as the source of failure. Again this a dummy record created to test the membership sign-up process, so again I deleted it and the linked contribution record and tried again. The scheduled job log threw up another record as the cause of failure, and I deleted that. Then another - but this last record was genuine, linked to a real membership record and contribution record - I don't want to delete it.

So I'm now stuck. No idea why the scheduled job is failing. As far as I can see none of the contacts in Civi has been sucecssfully pushed into QBO so far.

**Comment by agileware-justin** [comment]
@Upperholme what are the versions installed for accountsync and civiquickbooks extensions?

**Comment by agileware-fj** [comment]
@Upperholme this may not be relevant anymore, but QBO seems to treat the colon character as a separator for hierarchical fields and may reject it everywhere else.

Are you still having these issues?
