### ISSUE TITLE
'NOT IN' is not a valid option for field accounts_status_id

### ISSUE THREAD

**Issue by digifish** [agileware/au.com.agileware.civiquickbooks#44]
On Civicrm 5.60, with civiquickbooks 2.9.3 and account sync 1.5

I kept getting this message trying to push invoices to QB:
`Finished execution of Civiquickbooks Invoice Push Job with result: Failure, Error message: Invoice Push aborted due to: 'NOT IN' is not a valid option for field accounts_status_id`

I'm guessing this might be an issue with the definitions created Account Sync?

**Comment by axelady** [comment]
The fix is in master branch of account sync.  Version 1.5 (Feb 26) which is the latest release doesn't have it.
https://github.com/eileenmcnaughton/nz.co.fuzion.accountsync/issues/75 
https://github.com/eileenmcnaughton/nz.co.fuzion.accountsync/pull/76 was merged to master on Jun 29.

**Comment by agileware-justin** [comment]
Solution, update to latest Account Sync.
