### ISSUE TITLE
This extension generating thousands of small text files in my log directory.

### ISSUE THREAD

**Issue by Upperholme** [agileware/au.com.agileware.civiquickbooks#46]
I've just become aware that my ConfigAndLg directory contains thousands of text files with names like '89997-Response-1675246516-0.txt'.

Looking at a few of them it appears that they are related to our use of this extension. The files appear to be in pairs, one being a request and the other being a response.

Is this normal behaviour?

**Comment by agileware-justin** [comment]
Looks like the QuickBooks PHP API is doing that @Upperholme

**Comment by Upperholme** [comment]
OK. So, if it is normal behaviour, and your response isn't clear on that point, is it OK if I just delete all these files, or should I be dealing with them in some other way? They may be resulting from errors and problems that I'm seeing with the sync. Maybe I should just disable the extension until I can work out what's needed to get things working smoothly?

**Comment by agileware-justin** [comment]
@Upperholme I've only had a very quick look at the source of those files. I do agree that it's not optimal to be creating them and it is something that should be addressed, the timeframe at this stage is unclear.
