### ISSUE TITLE
Stale Object Error

### ISSUE THREAD

**Issue by BrianDouglassDigital** [agileware/au.com.agileware.civiquickbooks#52]
Hi.
On an install I am getting Stale Object Errors and i cannot see a way of resolving these.

 "error_data": "{\"failures\":1,\"error\":[\"Stale Object Error : You and <Civi Users Name> were working on this at the same time. <Civi Users Name> finished before you did, so your work was not saved.\"]}",

The API refers to a synctoken - is there any way of forcing this to refresh?

**Comment by agileware-fj** [comment]
@BrianDouglassDigital are these happening on Contact objects?

The local token is supposed to be updated during Contactpull runs, although I'm not sure this is working effectively.
