### ISSUE TITLE
Set up with Quickbooks UK

### ISSUE THREAD

**Issue by xpdientUK** [agileware/au.com.agileware.civiquickbooks#6]
I'm a day into this and struggling to match the Account Type with Quickbooks.
I get this error when doing the Invoice Push scheduled job

Finished execution of Civiquickbooks Invoice Push Job with result: Failure, Error message: Not all records were saved [
    "Failed to store 130 with error No valid line items in the Invoice to push. No matching Item found in Quickbooks Online for accounting code 67 (financial type 5)."
]
Financial type 5 is the ID of the financial type in CiviCRM.
So I'm trying to map this to a revenue or income code in Quickbooks Online and failing. 
And I don't know whether my error is in Quickbooks Online or CiviCRM.

On the Quickbooks Chart of Account, there are no codes that I can see.
Happy to pay someone a fee to configure this correctly for me.

Also happy to provide a dot-to-dot revision to the readme.md file.

**Comment by xpdientUK** [comment]
Further to this I have made progress. The documentation is incorrect at least for the UK.

You also need to use the Quickbooks API to get the name of the tax rate.

So the scheduled job still does not work, but now shows no error.

Full message: 
Finished execution of Civiquickbooks Invoice Push Job with result: Failure, Error message: Not all records were saved [
    {}
]

**Comment by xpdientUK** [comment]
Further to this I have made progress. The documentation is incorrect at least for the UK.

You also need to use the Quickbooks API to get the name of the tax rate.

So the scheduled job still does not work, but now shows no error.

Full message: 
Finished execution of Civiquickbooks Invoice Push Job with result: Failure, Error message: Not all records were saved [
    {}
]

**Comment by agileware-fj** [comment]
@xpdientUK Just to make sure – have you set up Tax & Invoicing in CiviCRM so that your financial types have a tax account which is mapped to the **Name** of the tax rate in QBO?

For non-US regions we retrieve the TaxCode via the Quickbooks API using the name that's stored as the acctgcode of your tax "Financial Account" in CiviCRM.

**Comment by xpdientUK** [comment]
OK I mapped the name of the Tax Rate in Quickbooks which I got via the API here
{
    "Name": "20.0% ECS",
    "Description": "EC Services Standard",
    "Active": true,
    "Hidden": true,
    "Taxable": true,
    "TaxGroup": true,
    "SalesTaxRateList": {
     "TaxRateDetail": []
    },
......
 So in CiviCRM my VAT accounting code is 20.0% ECS

I'm now back to  schedule job error  

"Failed to store 131 with error No valid line items in the Invoice to push. No matching Item found in Quickbooks Online for accounting code ClubGuests Data Entry (financial type 5)."
]

**Comment by agileware-fj** [comment]
Can you please confirm if you have a Product / Service ("Sales / Products and Services" in QBO) with the name "ClubGuests Data Entry".
If your product/service has a category &. subcategory, you may need to include them in the acctg code, separated by colons, i.e. "Category:ClubGuests Data Entry" or "Category:Sub-category:ClubGuests Data Entry"
It looks like this should be the same for the UK as for AU which we developed this on.

**Comment by agileware-fj** [comment]
The issue here was actually that the QBO app's access token has timed out, but authentication errors were not reported well.  This has been improved in release 2.3 so that such errors are shown in the Scheduled job log.
