### ISSUE TITLE
Reverse workflow support?

### ISSUE THREAD

**Issue by adixon** [agileware/au.com.agileware.civiquickbooks#7]
Does this extension support a read-only-from-quickbooks workflow? i.e. just pulling contacts and contributions from quickbooks and creating them in CiviCRM?

**Comment by jusfreeman** [comment]
G'day @adixon - it's possible to do a contact pull from QBO, there's a contact pull job included with the account sync extension. But pulling invoices from QBO into CiviCRM is not something that's supported.

**Comment by adixon** [comment]
Thanks. I don't know anything about QBO, so forgive my ignorance. Does pulling invoices from QBO to CiviCRM sound like something that could be done? Would you be open to adding in the functionality, via a PR from me?

**Comment by jusfreeman** [comment]
> Does pulling invoices from QBO to CiviCRM sound like something that could be done?

Yes

> Would you be open to adding in the functionality, via a PR from me?

@adixon go for it!
